[package]
name = "aoc2020"
version = "0.1.0"
authors = ["James Peach <jpeach6@bloomberg.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools= {version="^0.9.0"}
#scan_fmt= {version="^0.2.5"}
regex = "1"
